#+TITLE: Orga

#+begin_export html
<Magic>org-mode 💙 JavaScript</Magic>
#+end_export

* What Is It

=Orga= is a flexible org-mode syntax parser. It parses org content into AST ([[https://en.wikipedia.org/wiki/Abstract_syntax_tree][Abstract Syntax Tree 🌲]]). And it's written in JavaScript.

* Why
org-mode is simply a superior format than other more popular ones, but it's mostly trapped inside emacs. It's so good that it even becomes the reason to learn and use emacs for a lot of people (me included). But it's too good to not share with the rest of the world. If it can run in JavaScript, it can run on anything.

* Compatible Eco-systems
It integrates natively with popular tools.

** [[https://unifiedjs.com][Unified]]

#+BEGIN_QUOTE
☔️ interface for parsing, inspecting, transforming, and serializing content through syntax trees
#+END_QUOTE

The =orga= parser is completely compatible with unified. Which means you get to take advantage of the works of others put into the pipeline. [[https://github.com/retextjs/retext][linting for natural language]], [[https://alexjs.com][correct your writing]], [[https://wooorm.com/write-music/][write music]]? etc.

** [[https://webpack.js.org][Webpack]]

** [[https://www.gatsbyjs.com][Gatsby]]

#+BEGIN_QUOTE
Build blazing fast, modern apps and websites with React
#+END_QUOTE
