#+TITLE: Orga

#+BEGIN_QUOTE
org-mode with JavaScript
#+END_QUOTE

Are you sick of the fact that every body is supporting markdown format, like
it's the best thing in the world, and no body cares about the mighty [[https://orgmode.org][org-mode]]?
Well, Orga is here to change that.

* What Is It

Orga is a flexible org-mode syntax parser. It parses org content into AST
(Abstract Syntax Tree), then what you can do with it is only limited by your own
imagination.

* What It Can Do

Like I said, with AST at hand, you can do literally anything with it. The AST is
compatiable with the super awesome [[https://unifiedjs.github.io][unified]]. Witch means you can plug it right
into the existing system and established flows. Here are a couple of ideas:

- [X] transform your org-mode document into HTML
- [X] publish your org-mode notes with one of the most popular static site generators
- [ ] build a emacs-less cli for org-mode (working on this)
- [ ] natural language processing with [[https://github.com/retextjs/retext][retext]] and it's ever growing [[https://github.com/retextjs/retext/blob/master/doc/plugins.md][plugin ecosystem]]
- [ ] make your own GTD system with fancy UI and stuff
- [ ] automate your workflow with org-mode

* How Does It Work
