export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ border: '1px solid black', padding: '1rem' }}>
        {children}
      </body>
    </html>
  )
}
